name: xau-alerts

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # jalan tiap 30 menit

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOLDAPI_KEY: ${{ secrets.GOLDAPI_KEY }}
        run: python app.py
